name: deploy-search

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
#    paths:
#      - 'aspnetapp/**'

env:
  REGISTRY_IMAGE: egorksv/busybox
  DOCKERFILE: Dockerfile
  DEPLOYMENT_NAME: busybox

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ env.REGISTRY_IMAGE }}
        # generate Docker tags based on the following events/attributes
        #     pattern: '^release\.(?P<branchname>.*)-(?P<buildnumber>\d+)\.(?P<githash>.*)\.(?P<timestamp>\d+)'
        tags: |
          type=ref,enable=true,prefix=release.,suffix=-${{ github.run_number }}.{{sha}}.{{date 'YYYYMMDDHHmmss'}},event=branch
          type=raw,value=latest,enable=true

    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}"
        file: ${{ env.DOCKERFILE }}
        push: true
        tags:  ${{ steps.meta.outputs.tags }}

    - name: curl
      uses: enflo/curl-action@master
      with:
        curl: ${{ secrets.FLUXCD_WEBHOOK }}
